# -*- coding: utf-8 -*-
"""data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjJYosdsGhGoosJCrun6Ev9X9WfPXjTY

# AI-LEGAL-AID-ASSISTANCE
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install chromadb --only-binary=:all:

!pip install langchain_community langchain_chroma

!pip install pymupdf

!pip install langchain-text-splitters

!pip install -qU langchain-chroma chromadb

!pip install groq

"""important libraries to be imported"""

from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyMuPDFLoader
import os
from langchain_community.vectorstores import Chroma
import pickle

"""# Preprocessing of Constitution PDF"""

file_path = os.path.join(r"/content/drive/MyDrive/SIC_Project/Constitution.pdf")

#Splitting document pagewise using PyMuPdf
loader = PyMuPDFLoader(file_path)
data = loader.load()
data[0]

"""## We index the preamble and articles separately"""

# articles short
#Pages 3 to 31 contains the  introduction
articles_short = data[3:31]
articles_short[0]

# preamble
preamble = data[31]
preamble

articles = data[32:283]

print(articles[0].page_content)

##code to remove headers  and footers from pdf
import re
for art in articles:
  art.page_content = re.split(r'_{2,}', art.page_content)[0].strip()

"""We split the article content based on parts since constitution is divided into 25 PARTS"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

separator = "PART "  # Common chapter heading pattern

# Initialize the RecursiveCharacterTextSplitter with your chapter separator
text_splitter = RecursiveCharacterTextSplitter(
    separators=[separator],  # List of separators used to split the document
    chunk_size=1000,         # Maximum size of each split chunk
    chunk_overlap=100          # No overlap between splits
)

# Concatenate the 'page_content' of all Document objects into a single string
text = "".join([doc.page_content for doc in articles])

# Split the combined text by chapters
chapters = text_splitter.split_text(text)
chapters = chapters[1:]

for i in range(len(chapters)):
  print(f"part({i}) {chapters[i]}")
  print("\n\n")

def split_article_wise(chapter):
  """ Split the text based on Articles"""
  sections = re.split(r'(?=\n\d+\[?\d*[a-zA-Z]?[a-zA-Z]?\.\s)', chapter)
  # Optional: Strip leading/trailing whitespaces from each section
  sections = [section.strip() for section in sections]
  return sections

articles=[]
for chapter in chapters:
  articles.append(split_article_wise(chapter))

def cleaning_articles(arti):
  """Cleaning the articles text for unwanted special characters"""
  cl_art=[]
  for i in arti:
    pattern = r'^\d+\['
    if re.match(pattern, i):
      pos=arti.index(i)
      i = i.replace(i[:2], "", 1)
      arti[pos] = i
      cl_art.append(i)
    else:
      cl_art.append(i)
  return cl_art

docs = [cleaning_articles(i) for i in articles]

def adding_tag(docs):
  '''For adding Article keyword before each article number'''
  d=[docs[0]]
  for i in range(1,len(docs)):
    docs[i] = "Article " + docs[i]
    d.append(docs[i])
  return d

documents = [adding_tag(i) for i in docs]

nn =[i[1:] for i in documents]

nn[0][0].split(".")[0]

nn[0]

[j.split(".")[0]  for i in nn for j in i]

const = [" ".join(i) for i in documents]

const[0].replace("\n"," ")

# Code to generate Chapter names inorder to add in the Metadata
z2_list=[]
for chapter in chapters:
  z2 = chapter.split('\n')[0]
  z2_list.append(z2)
z2_list

len(z2_list)

part_names = ['The union and its territories',
 'Citizenship',
 'Fundamental rights',
 'Directive principles of state policy',
 'Fundamental duties ',
 'The union',
 'The states',
 'The States in Part B of the First Schedule',
 'The union territories',
 'The panchayats',
 'The municipalities',
 'The co-operative societies',
 'The scheduled and tribal areas',
 'Relations between the union and the states',
 'Finance, property, contracts and suits',
 'Trade, commerce and intercourse within the territory of india',
 'Services under the union and the states',
 'Tribunals',
 'Elections',
 'Special provisions relating to certain classes',
 'Official language',
 'Emergency provisions',
 'Miscellaneous',
 'Amendment of the constitution',
 'Temporary, transitional and special provisions',
 'Short title, commencement,authoritative text in hindi and repeals']

len(part_names)

z1_list = [" ".join(j.capitalize() for j in i.split(" ")) for i in part_names]

z2_list = [i.strip() for i in z1_list]

z2_list,z1_list

"""We use proper chunking of 1000 and overlap of 300"""

from langchain_text_splitters import CharacterTextSplitter
chunked_list = []
t_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=300,
    length_function=len,
    is_separator_regex=True,
)

for i,chapter in enumerate(const):
  # adding meta data here li is the list with name of chapters which we created above
  metadatas = [{"source": "https://cdnbbsr.s3waas.gov.in/s380537a945c7aaa788ccfcdf1b99b5d8f/uploads/2024/07/20240716890312078.pdf",
                "source_name": "Indian Constitution", "country":"India","db_owner":"LawGlance","part":z2_list[i],"part_name":z1_list[i]}]
  # Use the splitter to split each chapter into chunks
  chunks = t_splitter.create_documents([chapter],metadatas=metadatas)
  # Append the chunks to the chunked_list
  chunked_list.append(chunks)

chunked_list[1]

def flatten_extend(matrix):
  flat_list = []
  for row in matrix:
    flat_list.extend(row)
  return flat_list

do = flatten_extend(chunked_list)
do

"""Save those chunks into pkl file"""

import pickle

with open("/content/drive/MyDrive/SIC_Project/constitution_chunks.pkl", "wb") as f:
    pickle.dump(do, f)



"""# Processing IPC Dataset"""

import pandas as pd

ipc_df = pd.read_csv('/content/drive/MyDrive/SIC_Project/ipc_sections.csv')
print("IPC sections loaded into 'ipc_df'.")
ipc_df.head()

from langchain_core.documents import Document

ipc_docs = []
for index, row in ipc_df.iterrows():
    # Combine relevant columns into page_content
    page_content = f"Description of {row['Section']}: {row['Description']}\nOffense: {row['Offense']}\nPunishment: {row['Punishment']}"

    # Define metadata, including existing general metadata and the specific section
    metadata = {
        "source": "/content/drive/MyDrive/SIC_Project/ipc_sections.csv",
        "source_name": "Indian Penal Code",
        "country": "India",
        "db_owner": "LawGlance",
        "section": row['Section']
    }

    ipc_docs.append(Document(page_content=page_content, metadata=metadata))

print(f"Created {len(ipc_docs)} Document objects from ipc_df.")
print("Example Document:")
print(ipc_docs[0])

from langchain_text_splitters import RecursiveCharacterTextSplitter

# Initialize the RecursiveCharacterTextSplitter
# Using similar parameters as for the Constitution to maintain consistency
t_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=300,
    length_function=len,
    is_separator_regex=False, # Changed to False as we are splitting general text now
)

# Chunk the ipc_docs
chunked_ipc_docs = t_splitter.split_documents(ipc_docs)

print(f"Original IPC documents: {len(ipc_docs)}")
print(f"Chunked IPC documents: {len(chunked_ipc_docs)}")
print("Example of a chunked IPC document:")
print(chunked_ipc_docs[0])

output_pickle_path = "/content/drive/MyDrive/SIC_Project/ipc_section.pkl"
with open(output_pickle_path, "wb") as f:
    pickle.dump(chunked_ipc_docs, f)

print(f"Chunked IPC documents saved to {output_pickle_path}")

"""# Embedding into vector_database"""

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
import os

# Initialize embedding model
embedding_model = HuggingFaceEmbeddings(
    model_name="BAAI/bge-small-en-v1.5"
)

# Define persist directory
persist_directory = "/content/drive/MyDrive/SIC_Project/vector_db/legal_bot_database"

# Create Chroma vector store instance
# Note: If the directory exists, Chroma will load the existing collection.
# If it doesn't exist, it will create a new one.
vector_store = Chroma(persist_directory=persist_directory, embedding_function=embedding_model)

print("Embedding model and Chroma vector store initialized successfully.")

retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 5})

import pickle

with open("/content/drive/MyDrive/SIC_Project/constitution_chunks.pkl", "rb") as f:
    docs = pickle.load(f)

with open("/content/drive/MyDrive/SIC_Project/ipc_section.pkl", "rb") as f:
    chunked_ipc_docs = pickle.load(f)

vector_store.add_documents(documents=docs)
print("Constitution added to Chroma vector store successfully.")

vector_store.add_documents(documents=chunked_ipc_docs)
print("IPC sections added to Chroma vector store successfully.")

"""# LLM"""

!pip install groq

from groq import Groq

# ---------------------------------------------
# Initialize Groq API
# ---------------------------------------------
client = Groq(
    api_key=""
)

# ---------------------------------------------
# Legal Aid Assistant Function
# ---------------------------------------------
def legal_assistant(question):

    # Retrieve documents from RAG
    docs = retriever.invoke(question)

    # Convert retrieved docs to context
    context = "\n".join([doc.page_content for doc in docs])

    # If no relevant context found
    if not context.strip():
        return "Please ask relevant questions related to legal aid only."

    prompt = f"""
You are an AI Legal Aid Assistant designed to help users understand laws.

STRICT RULES:

1. Answer ONLY using the provided legal context and write in a para.
2. Don't add according to context just answer based on context.
2. If the question is NOT related to legal matters OR the context does not contain the answer,
respond ONLY with:

Please ask relevant questions related to legal aid only.

3. Do not generate information outside the context.

Legal Context:
{context}

User Question:
{question}

Answer strictly based on the context above.
"""

    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "system",
                "content": "You are a professional legal aid assistant."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content

"""# Test"""

retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": 5})
query = "Who is right education?"
print(query)
print("\n")
results = retriever.invoke(query)
for(result) in results:
  print(result.page_content)
# print(legal_assistant(query))

!pip install fastapi uvicorn pyngrok nest_asyncio

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# from fastapi import FastAPI
# from pydantic import BaseModel
# from fastapi.middleware.cors import CORSMiddleware
# 
# app = FastAPI()
# 
# app.add_middleware(
#     CORSMiddleware,
#     allow_origins=["*"],
#     allow_credentials=True,
#     allow_methods=["*"],
#     allow_headers=["*"],
# )
# 
# class Query(BaseModel):
#     question: str
# 
# @app.post("/predict")
# def predict(q: Query):
#     result = legal_assistant(q.question)
#     return {"answer": "Nyaya Sahayak: " + result}

from pyngrok import ngrok

# Replace 'YOUR_AUTH_TOKEN' with your actual ngrok authtoken
# You can get this from your ngrok dashboard after signing up:
# https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.set_auth_token("3AdYCvYqRL3cOvWTrEhxu0RYrmP_6ayCTvWPuQwYCPLWMqxid")

public_url = ngrok.connect(8000)
print(public_url)

!uvicorn app:app --host 0.0.0.0 --port 8000 &

